### ISSUE TITLE
Prevent deployment on templates

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/node-reusable-workflows#37]
- [x] node-base-template
- [x] node-template-template

**Comment by ryabukhinstep** [comment]
Repos:

- https://github.com/Byndyusoft/node-base-template
- https://github.com/Byndyusoft/node-typescript-template

**Comment by KillWolfVlad** [comment]
We disable deploy action in this repos:

![image](https://user-images.githubusercontent.com/18448635/192080830-d3818366-8dc6-4b4c-b2ff-96bdfc1e3fcf.png)

![image](https://user-images.githubusercontent.com/18448635/192080855-f9f36859-4bb7-4d08-9545-bb65112a3d76.png)
