### ISSUE TITLE
Выработать стратегию дополнительного обката мажорных версий и поддержки предыдущих мажорных релизов

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/node-reusable-workflows#44]
Цель:
- [x] Иметь возможность какое-то время потестировать следующий мажорный релиз
- [x] Иметь возможность поддерживать предыдущую мажорную версию столько сколько это потребуется

Решение:

Надо использовать встроенные механизмы semantic-release.

Для обката следующей мажорной версии использовать ветку `next`. Для поддержки старых релизов создать например ветку `v1.x` .

Что-бы все это работало стоит изменить свой `.releaserc.yaml`:

```yaml
branches:
  - name: master
  - name: next
    prerelease: rc
  - name: v1.x
    range: 1.x
```

DoD:
- [x] Найти задачу чтобы сделать отдельную репу для тестов
- [x] Проверить что при релизе из ветки next (ставиться какой-то суффикс - опционально) и в channel next
- [x] Люди которые зашли в npm - поняли что это не последняя версия пакета (yarn install не ставит эту версию)
- [x] Зафиксировать во внутренней базе данных

**Comment by litichevskiydv** [comment]
@KillWolfVlad добавит DoD

**Comment by litichevskiydv** [comment]
К следующему стендапу описываем DoD с целями и вариантами реализации

**Comment by KillWolfVlad** [comment]
Нужно собрать метрику того, как долго требуется поддержка старых версий.
